### ISSUE TITLE
Adding a node failed.

### ISSUE THREAD

**Issue by snoby** [CiscoCloud/mantl#1777] opened 2016-07-29 21:03 UTC
Using v1.2 I deployed to AWS.  After everything was up and health I went back to my aws.tf file and changed the number of works from 4 to 7.  Next i ran:
```
terraform get
terraform plan
terraform apply
```
I noticed in the logs that the running lvm volumes seemed to be removed from running workers and then the terraform apply timed out on creating the lvm volumes.

[terraform_log.txt](https://github.com/CiscoCloud/mantl/files/391376/terraform_log.txt)

ansible 1.9.6
Python 2.7.10
mantl version 1.2 from tag
Terraform v0.6.15

**Comment by siddharthist** [comment] 2016-07-29 21:23
Closing as a duplicate of #1339. Thanks for reporting this, @snoby!

**Closed by siddharthist** 2016-07-29 21:23 UTC
