### ISSUE TITLE
TASK: [consul | wait for leader]

### ISSUE THREAD

**Issue by tymofii-polekhin** [CiscoCloud/mantl#1472] opened 2016-05-23 14:14 UTC
Hello,
`TASK: [consul | wait for leader]` failed both times i ran playbook.
Also, 
```
[cloud-user@mantl-control-01 ~]$ consul members
Node              Address           Status  Type    Build  Protocol  DC
mantl-control-01  10.10.10.60:8301  alive   server  0.6.4  2         openstack
mantl-control-02  10.10.10.61:8301  alive   server  0.6.4  2         openstack
mantl-control-03  10.10.10.59:8301  alive   server  0.6.4  2         openstack
mantl-edge-01     10.10.10.53:8301  alive   client  0.6.4  2         openstack
mantl-worker-001  10.10.10.55:8301  alive   client  0.6.4  2         openstack
mantl-worker-002  10.10.10.54:8301  alive   client  0.6.4  2         openstack
mantl-worker-003  10.10.10.57:8301  alive   client  0.6.4  2         openstack
mantl-worker-004  10.10.10.58:8301  alive   client  0.6.4  2         openstack
mantl-worker-005  10.10.10.56:8301  alive   client  0.6.4  2         openstack
```
No known peers error
```
2016/05/23 13:48:44 [INFO] serf: EventMemberJoin: mantl-control-02 10.10.10.61
2016/05/23 13:48:44 [INFO] serf: Re-joined to previously known node: mantl-worker-003: 10.10.10.57:8301
2016/05/23 13:48:44 [INFO] consul: adding LAN server mantl-control-03 (Addr: 10.10.10.59:8300) (DC: openstack)
2016/05/23 13:48:44 [INFO] consul: adding LAN server mantl-control-02 (Addr: 10.10.10.61:8300) (DC: openstack)
2016/05/23 13:48:44 [INFO] agent: (LAN) joined: 3 Err: <nil>
2016/05/23 13:48:44 [INFO] agent: Join completed. Synced with 3 initial agents
2016/05/23 13:48:45 [WARN] raft: EnableSingleNode disabled, and no known peers. Aborting election.
2016/05/23 13:49:07 [ERR] agent: coordinate update error: No cluster leader
2016/05/23 13:49:13 [ERR] agent: failed to sync remote state: No cluster leader
2016/05/23 13:49:23 [ERR] agent: coordinate update error: No cluster leader
2016/05/23 13:49:23 [INFO] serf: EventMemberLeave: mantl-control-02 10.10.10.61
2016/05/23 13:49:23 [INFO] consul: removing LAN server mantl-control-02 (Addr: 10.10.10.61:8300) (DC: openstack)
2016/05/23 13:49:27 [INFO] serf: EventMemberJoin: mantl-control-02 10.10.10.61
2016/05/23 13:49:27 [INFO] consul: adding LAN server mantl-control-02 (Addr: 10.10.10.61:8300) (DC: openstack)
2016/05/23 13:49:38 [ERR] agent: failed to sync remote state: No cluster leader
2016/05/23 13:49:44 [ERR] agent: coordinate update error: No cluster leader
2016/05/23 13:50:03 [ERR] agent: coordinate update error: No cluster leader
```
retry_join configured correctly
```
[cloud-user@mantl-control-01 ~]$ sudo cat /etc/consul/consul.json
{
  "datacenter": "openstack",
  "advertise_addr": "10.10.10.60",
  "node_name": "mantl-control-01",
  "rejoin_after_leave": true,
  "domain": "consul",
  "log_level": "warn",
  "retry_join": [ "10.10.10.60", "10.10.10.61", "10.10.10.59" ],
  "server": true,
  "bootstrap_expect": 3,
```

Info:
```
[17:02][tpol][mantl] git:(master*): ansible --version
ansible 1.9.6
  configured module search path = None
```
```
[17:06][tpol][mantl] git:(master*): python --version
Python 2.7.10
```
`commit 65aa7837162ea15b2687ebcd61424c9bb1853501`
`Cisco OpenStack`
```
[17:08][tpol][mantl] git:(master*): ~/ansible/terraform/terraform version
Terraform v0.6.6
```

**Comment by tymofii-polekhin** [comment] 2016-05-24 09:42
https://github.com/hashicorp/consul/issues/993

**Comment by ryane** [comment] 2016-05-24 10:13
I am not sure how to reproduce this problem. Can you confirm that you have connectivity across the consul ports between all of your control nodes? There was a similar issue reported with another Cisco OpenStack install and it appeared to be due to a problem with communication between control nodes. I added you to a gitter room where it was being discussed.

**Comment by tymofii-polekhin** [comment] 2016-05-24 10:21
@ryane the issue is fully described here https://github.com/hashicorp/consul/issues/993
You can reproduce this by issuing `sudo systemctl restart consul` on `consul server` nodes
We can fix this by custom consul restart script which will update `peers.json` every restart, or we can modify `consul.service` on `server nodes` to issue `SIGTERM` instead of `SIGINT`

**Comment by ryane** [comment] 2016-05-24 11:28
I cannot reproduce the problem by running `systemctl restart consul` on a control server node. I *can* reproduce if I restart consul on all control nodes at the same time. This is not unexpected b/c it can break the quorum and is something to avoid (it's why we try to do rolling restarts whenever a consul update is required). We have an in-progress PR (#948 - needs more testing) that can fix a broken consul cluster by updating peers.json (based on https://www.consul.io/docs/guides/outage.html) but I don't think we'd considered automating that as part of the consul systemd service. Looping in @stevendborrelli and @ChrisAubuchon for their feedback.

**Comment by tymofii-polekhin** [comment] 2016-05-24 12:09
I catched this issue during 2 fresh deployments, so its not something unusual :)

**Comment by bingoarunprasath** [comment] 2016-05-25 09:21
I faced the same issue with Cisco OpenStack install yesterday. I was provisioning 2 control nodes at that time. The servers were able to reach consul ports among them and consul members listed all the nodes, but not sure what went wrong. Later I re-provisioned  with 1 controller nodes to test my patch. I will gather more details next time I encounter the issue.

**Comment by ChrisAubuchon** [comment] 2016-05-25 13:28
@bingoarunprasath Two control nodes will never work because of the Consul's `(n/2)+1` quorum. With two control nodes Consul loses quorum when a single instance is restarted and the instances are restarted several times as part of the Mantl deployment.

**Comment by bingoarunprasath** [comment] 2016-05-26 01:41
@ChrisAubuchon : Thanks for the clarification

**Comment by davidfic** [comment] 2016-06-03 20:59
I am running into this same issue. 

[Here is the output from my run](https://gist.github.com/davidfic/6c890002db06ecd8865f51af107443e7)

If I log into any of the control nodes and try to list the cluster membership I get the following:

     [centos@ip-10-1-2-98 ~]$ consul members
     Error connecting to Consul agent: dial tcp 127.0.0.1:8400: getsockopt: connection refused

If I log into any of the other servers I see that the only list themselves as members:

     [centos@ip-10-1-1-27 ~]$ consul members
     Node              Address         Status  Type    Build  Protocol  DC
     mantl-worker-004  10.1.1.27:8301  alive   client  0.6.4  2         aws-us-west-2

Looking at the logs on the control servers I see this:

    Jun  3 20:50:14 ip-10-1-2-98 systemd: Started Consul is a tool for service discovery and configuration..
    Jun  3 20:50:14 ip-10-1-2-98 systemd: Starting Consul is a tool for service discovery and configuration....
    Jun  3 20:50:14 ip-10-1-2-98 consul: ==> Error decoding '/etc/consul/acl.json': invalid character '}' looking for beginning of object key string
    Jun  3 20:50:14 ip-10-1-2-98 systemd: consul.service: main process exited, code=exited, status=1/FAILURE

I've run through this setup a few times and each time I'm getting the exact same error. 

Please let me know if you need any other info.

**Comment by davidfic** [comment] 2016-06-03 21:30
I've figure out this issue. it seems there is a trailing common in the acl.json.j2 template that is causing it to fail. 

    {
    {% if consul_is_server %}
        "acl_master_token": "{{ consul_acl_master_token }}",
        "acl_default_policy": "{{ consul_acl_default_policy }}",
        "acl_down_policy": "{{ consul_acl_down_policy }}",
    {% endif %}
    }

I just removed the final comma and re-ran the playbook and the leader was elected.

**Comment by siddharthist** [comment] 2016-06-03 21:52
@davidfic I think that's fixed in the latest master. Check out the template: https://github.com/CiscoCloud/mantl/blob/b9e188e88385e35e11433161eef992619361e72b/roles/consul/templates/acl.json.j2#L5

**Comment by davidfic** [comment] 2016-06-03 23:18
OK It was my bad. I had removed the else clause since I had commented out the datacenter line in mantl.yml. I put it back to normal and uncommented the datacenter line and it installed as expected. 

Sorry for the confusion. 

Now I am getting another failure documented here #1437

**Comment by siddharthist** [comment] 2016-06-06 15:10
@davidfic @bingoarunprasath @tymofii-polekhin Have any of you had the chance to test the playbook in #948 during a Consul leader election failure?

**Comment by davidfic** [comment] 2016-06-06 15:27
I haven't, but after going over all my steps the majority of my problems were self inflicted. 

I've managed to clear up all the issues around Consul starting. The main issue that I was running into was in Step 4 of the docs:

> You’ll want to change consul_acl_datacenter to your preferred ACL datacenter. If you only have one datacenter, you can remove this variable.

Removal of that variable causes the failure. It should be noted that the datacenter variable in the .yml file and .tf must be the same.

**Comment by siddharthist** [comment] 2016-06-21 15:49
Closing since #948 has been merged. If anyone sees this reproducably in master, please reopen.

**Closed by siddharthist** 2016-06-21 15:49 UTC
