### ISSUE TITLE
elasticsearch-executor fails to load on a worker node.

### ISSUE THREAD

**Issue by shali-mor** [CiscoCloud/mantl#1195] opened 2016-03-01 23:30 UTC
Having 3 controls , two worker and 1 edge machine, 
running addons/elk.yml ansible script , the elasticsearch executor fails to load :  (from stderr) 
```
I0301 23:22:49.115537  9782 logging.cpp:172] INFO level logging started!
I0301 23:22:49.115803  9782 fetcher.cpp:414] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/3cb967f5-d1ee-475d-891f-be0efe0d50d6-S0\/root","items":[{"action":"BYPASS_CACHE","uri":{"extract":true,"value":"http:\/\/mi-worker-001.cisco.com:56062\/get\/elasticsearch-mesos-executor.jar"}}],"sandbox_directory":"\/var\/lib\/mesos\/slaves\/3cb967f5-d1ee-475d-891f-be0efe0d50d6-S0\/frameworks\/e1ea903b-12ca-4e7c-85e2-4210d02e5e2b-0000\/executors\/9d087794-db61-4c89-8f52-297e11abf77e\/runs\/e16beaeb-fa11-4c6c-983d-c77fe093c61d","user":"root"}
I0301 23:22:49.117177  9782 fetcher.cpp:369] Fetching URI 'http://mi-worker-001.cisco.com:56062/get/elasticsearch-mesos-executor.jar'
I0301 23:22:49.117192  9782 fetcher.cpp:243] Fetching directly into the sandbox directory
I0301 23:22:49.117208  9782 fetcher.cpp:180] Fetching URI 'http://mi-worker-001.cisco.com:56062/get/elasticsearch-mesos-executor.jar'
I0301 23:22:49.117221  9782 fetcher.cpp:127] Downloading resource from 'http://mi-worker-001.cisco.com:56062/get/elasticsearch-mesos-executor.jar' to '/var/lib/mesos/slaves/3cb967f5-d1ee-475d-891f-be0efe0d50d6-S0/frameworks/e1ea903b-12ca-4e7c-85e2-4210d02e5e2b-0000/executors/9d087794-db61-4c89-8f52-297e11abf77e/runs/e16beaeb-fa11-4c6c-983d-c77fe093c61d/elasticsearch-mesos-executor.jar'
Failed to fetch 'http://mi-worker-001.cisco.com:56062/get/elasticsearch-mesos-executor.jar': Error downloading resource: Couldn't resolve host name
Failed to synchronize with slave (it's probably exited)
```

from mesos : 
```
elasticsearch_mi-worker-002.node.consul_20160301T232839.294Z	elasticsearch-executor	FAILED	just now	just now	mi-worker-002.node.consul	Sandbox
```
from marathon : 
```
elastic search is running on worker1 only . 
```
**
please note that the behaviour is consistence (tryed more that 5 times with exact same errors)  

**

**Comment by siddharthist** [comment] 2016-03-02 00:34
@shali-mor Is the hostname "mi-worker-001.cisco.com" resolvable from both your workers? Can you post the output of
```
ansible all -i plugins/inventory/terraform.py -e @security.yml "dig +short mi-worker-001.cisco.com" 
```

**Comment by shali-mor** [comment] 2016-03-02 05:38
HI ,
for some reason , I get ‘no match’ , but it is the same answer for all workers/control/edge .

looking at consul UI ,  I see it recognises all nodes :



any status

passing

failing
EXPAND
mi-control-017 services
mi-control-027 services
mi-control-037 services
mi-edge-014 services
mi-worker-0014 services
mi-worker-002





On 2 Mar 2016, at 2:34 AM, Langston Barrett <notifications@github.com<mailto:notifications@github.com>> wrote:


@shali-mor<https://github.com/shali-mor> Is the hostname "mi-worker-001.cisco.com<http://mi-worker-001.cisco.com>" resolvable from both your workers? Can you post the output of

ansible all -i plugins/inventory/terraform.py -e @security.yml "dig +short mi-worker-001.cisco.com<http://mi-worker-001.cisco.com>"

**Comment by siddharthist** [comment] 2016-03-02 06:02
So it looks like one of the Mesos workers is trying to get a resource from the other, but can't resolve it because it is using an incorrect hostname (it should be <hostname>.node.consul_dns_domain>). Any ideas why Mesos would be using the wrong hostname for this task @ryane?

**Comment by ryane** [comment] 2016-03-02 13:43
hm, I'm not really sure - I do see *.consul on all my test clusters. @shali-mor when you look at Mesos, what are the hosts set to for your mesos agents (Slaves tab in the UI)?

Also, when you installed the elk addon, did you change the default configuration to change the number of elasticsearch nodes? By default, it tries to spin up 3 elasticsearch instances. If you only have two worker nodes, you're likely going to run into problems.

**Comment by shali-mor** [comment] 2016-03-02 14:02
HI ,
Feel free to look at my cluster at : http://173.39.240.80/ui/  (I’m leaving work for the rest of the day :) )


I have two workers there :
ID      Host    CPUs    Mem     Disk    Registered      Re-Registered
…891f-be0efe0d50d6-S0<http://173.39.240.80/mesos/#/slaves/3cb967f5-d1ee-475d-891f-be0efe0d50d6-S0>      mi-worker-002.node.consul       2       6.8 GB  44.2 GB 15 hours ago    15 hours ago
…a19f-8656d7607d14-S0<http://173.39.240.80/mesos/#/slaves/2d5d4159-2c15-4de3-a19f-8656d7607d14-S0>      mi-worker-001.node.consul       2       6.8 GB  44.2 GB 15 hours ago    15 hours ago


regarding the ELK configuration , I didn’t change anything…
should I use 3 workers to make ELK work ? it doesn’t sound right to me….

Shali.

On 2 Mar 2016, at 3:43 PM, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


hm, I'm not really sure - I do see *.consul on all my test clusters. @shali-mor<https://github.com/shali-mor> when you look at Mesos, what are the hosts set to for your mesos agents (Slaves tab in the UI)?

Also, when you installed the elk addon, did you change the default configuration to change the number of elasticsearch nodes? By default, it tries to spin up 3 elasticsearch instances. If you only have two worker nodes, you're likely going to run into problems.

**Comment by ryane** [comment] 2016-03-02 14:37
Yes, please review http://docs.mantl.io/en/latest/components/elk.html#default-configuration. We install 3 nodes by default for HA and data safety reasons. If you want fewer nodes, you have to customize the install.

**Comment by ryane** [comment] 2016-03-02 15:47
what does `hostname` return on your workers? it looks like the framework uses that to figure out where to download resources from. So, you need to make sure your hostnames are resolvable.

**Comment by shali-mor** [comment] 2016-03-03 10:54
Ok , great.
is there a way to add worker on the fly (on deployed system ?

Thanks
Shali.
On 2 Mar 2016, at 5:47 PM, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


what does hostname return on your workers? it looks like the framework uses that to figure out where to download resources from. So, you need to make sure your hostnames are resolvable.

**Comment by shali-mor** [comment] 2016-03-03 15:17
Hi ,

I have a setup with three workers (three control and one edge) , but its still not working .
(I run the command ansible-playbook -e @security.yml addons/elk.yml )

it seems that worker-001 is trying to download elasticsearch-mesos-executor.jar from mi-worker-002. with url : http://mi-worker-002.cisco.com:57006/get/elasticsearch-mesos-executor.jar<http://mi-worker-002.cisco.com> , however, the hostname is not resolvable.

Looking at /etc/hosts , I can see that there is a mapping from mi-worker-002 to a certain IP .  (not using cisco.com<http://cisco.com> suffix)

From within the machine (mi-worker-001) , I can ping mi-worker-002 but not mi-worker-002.cisco.com<http://worker002.cisco.com>

looking at the mesos logs of worker-001 :

3 14:18:52,142:14258(0x7fe164ee9700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2016-03-03 14:18:52,142:14258(0x7fe164ee9700):ZOO_INFO@log_env@716: Client environment:host.name=mi-worker-002.cisco.com<http://mi-worker-002.cisco.com>
2016-03-03 14:18:52,142:14258(0x7fe164ee9700):ZOO_INFO@log_env@723: Client environment:os.name=Linux


do you have a hint ?

Thanks,
Shali.

On 3 Mar 2016, at 12:54 PM, Shali Mor (shmor) <shmor@cisco.com<mailto:shmor@cisco.com>> wrote:

Ok , great.
is there a way to add worker on the fly (on deployed system ?

Thanks
Shali.
On 2 Mar 2016, at 5:47 PM, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


what does hostname return on your workers? it looks like the framework uses that to figure out where to download resources from. So, you need to make sure your hostnames are resolvable.

**Comment by ryane** [comment] 2016-03-03 17:28
As far as I can tell, the root of the problem is that your hostnames are not resolvable - the framework seems to depend on that. Are you on openstack? I think you have to tweak your setup so you don't end up with hostnames like *.cisco.com and instead get hostnames that are internally resolvable. But, I don't really know a lot about that.

**Comment by shali-mor** [comment] 2016-03-03 17:42
Thanks for the reply
I'm working on CCS and it seems like the normal behavior there . Have you checked ELK with CCS ? Is it working for you ?
I didn't change anything in the CCS configuration...

Thanks
Shali

On Mar 2, 2016, at 17:47, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


what does hostname return on your workers? it looks like the framework uses that to figure out where to download resources from. So, you need to make sure your hostnames are resolvable.

-

**Comment by ryane** [comment] 2016-03-03 18:22
I'm not familiar with CCS. I have tested with openstack and it does work but my environment has resolvable hostnames. If that is not an option on CCS, it may require changes to the Elasticsearch framework itself to support another mechanism to download resources: https://github.com/mesos/elasticsearch

**Comment by shali-mor** [comment] 2016-03-03 18:24
Ok
Maybe I'll open a case against CCS
IMHO , I think CCS should be one of your tested platforms as its Cisco open stack deployment...

Thanks
Shali

On Mar 3, 2016, at 20:22, Ryan Eschinger <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not familiar with CCS. I have tested with openstack and it does work but my environment has resolvable hostnames. If that is not an option on CCS, it may require changes to the Elasticsearch framework itself to support another mechanism to download resources: https://github.com/mesos/elasticsearch

-

**Comment by ryane** [comment] 2016-04-05 14:04
I'm going to close this for now. Please open a new issue if you are still having problems

**Closed by ryane** 2016-04-05 14:04 UTC
Labels: addons/elk
