### ISSUE TITLE
block storage mount path on edge nodes 

### ISSUE THREAD

**Issue by ipolyzos** [CiscoCloud/mantl#1228] opened 2016-03-04 09:01 UTC
I experience issues with block storage in edge nodes. When I attempt to use the default path **/dev/vdb** in several machines is failing with the message "already been used" changing this to /**dev/vdd** proceed and finalize the environment. However doing of so is failing again, in **edge ** nodes, ansible break cause can not find the path i.e /dev/vdd. I can see from OpenStack console that volume created and  attached in the specified path (i.e. /deb/vdd) but when i ssh into the machine I can not see the device (dev/vdd).

- Ansible version:  1.9.4
- Python version: 2.7.5
- Git commit hash or branch:  v1.0.2
- Cloud Environment: Openstacm
- Terraform version: 0.6.12

**Comment by stevendborrelli** [comment] 2016-03-05 18:11
To confirm, did `/dev/vdd` work on control & worker nodes?

**Comment by ipolyzos** [comment] 2016-03-05 21:42
Yes it worked in control and worker nodes. The only nodes affected are the edge ones.

**Comment by siddharthist** [comment] 2016-05-23 16:31
Is this a duplicate of #949?

**Comment by siddharthist** [comment] 2016-07-19 08:56
Closing as a duplicate of #949

**Closed by siddharthist** 2016-07-19 08:56 UTC
Labels: bug
