### ISSUE TITLE
Any updates on Azure deployment.

### ISSUE THREAD

**Issue by andreimc** [CiscoCloud/mantl#1500] opened 2016-06-05 08:27 UTC
I am looking at an azure deployment at the end of June, I am just wondering if any progress has been made on this #1269.

I know terraform is lacking support for Azure loadbalancer is a deployment possible without similar to bare metal?

**Comment by siddharthist** [comment] 2016-06-07 13:01
I think @stevendborrelli would be the one to ask

**Comment by siddharthist** [comment] 2016-06-15 12:44
Closing as a duplicate of #1269. We'll keep you updated @andreimc!

**Closed by siddharthist** 2016-06-15 12:44 UTC
