### ISSUE TITLE
docker hangs and hundreds of docker ps processes

### ISSUE THREAD

**Issue by kbroughton** [CiscoCloud/mantl#1490] opened 2016-05-31 03:41 UTC
This is affecting worker-001 only for me, just began after about 2 weeks of operation.  Perhaps triggered by trying to remove and re-install kibana framework after the UI failed.

- Ansible version (`ansible --version`):  1.9.4
- Python version (`python --version`):  Python 2.7.11 :: Anaconda 2.3.0 (x86_64)
- Git commit hash or branch:
master from May 18
commit e708bf4ee3b79c967069517136b1a8c0fe0d3cff
Author: Langston Barrett <langston.barrett@gmail.com>
Date:   Wed May 18 16:06:41 2016 -0500

    Add nginx config dirs to marathon role 
- Cloud Environment:  aws

sudo ps aux | docker 
shows hundreds of results like this:
root     19912  0.0  0.0 193428  2760 ?        S    02:48   0:00 sudo docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}
root     19913  0.0  0.0 256672 14088 ?        Sl   02:48   0:00 docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}
root     19995  0.0  0.0 193428  2760 ?        S    May30   0:00 sudo docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}
root     19996  0.0  0.0 256672 14432 ?        Sl   May30   0:00 docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}
root     20076  0.0  0.0 193428  2760 ?        S    May30   0:00 sudo docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}

I don't see anything abnormal in systemctl
```
^C[root@k4b4-mantl-worker-001 ~]# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-options.conf, 12-network-options.conf, 14-storage-options.conf, 20-ExecStart.conf
   Active: active (running) since Thu 2016-05-19 22:49:40 UTC; 1 weeks 4 days ago
     Docs: https://docs.docker.com
 Main PID: 25831 (docker)
   Memory: 3.9G
   CGroup: /system.slice/docker.service
           ├─ 4845 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 4002 -container-ip 172.17.0.9 -container-port 5601
           ├─ 6233 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 25826 -container-ip 172.17.0.8 -container-port 25826
           ├─ 6242 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 8125 -container-ip 172.17.0.8 -container-port 8125
           ├─ 6250 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5678 -container-ip 172.17.0.8 -container-port 5678
           ├─ 6259 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 1514 -container-ip 172.17.0.8 -container-port 1514
           ├─ 6543 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 7155 -container-ip 172.17.0.5 -container-port 3000
           ├─ 6549 docker-containerd-shim cdf29b5cae60ae63259d0cf33bb0bf224619ff1fc2aea35867a089b63636ff69 /var/run/docker/libcontainerd/cdf29b5cae60ae63259d0cf33bb0bf224619ff1...
           ├─ 6671 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 31573 -container-ip 172.17.0.6 -container-port 3000
           ├─ 6676 docker-containerd-shim afdac2ef5ce70a093eb181862bd6812cbd51775b56d29e7f03ac731d9741994e /var/run/docker/libcontainerd/afdac2ef5ce70a093eb181862bd6812cbd51775...
           ├─ 7068 docker-containerd-shim a5f1fb9e0a711319476e85f6b014c632802d0c599347f45b7289609355b21423 /var/run/docker/libcontainerd/a5f1fb9e0a711319476e85f6b014c632802d0c5...
           ├─ 8967 docker-containerd-shim 08c7b3c77cdcaa769198a41d620d887467941b15150a932c22abb8e0ace05556 /var/run/docker/libcontainerd/08c7b3c77cdcaa769198a41d620d887467941b1...
           ├─ 9606 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 25081 -container-ip 172.17.0.7 -container-port 8081
           ├─ 9612 docker-containerd-shim 7b850a1d614f08369b9eafe1fc5b85500fdfa6eb0b9fd37ddc0853ba5f00a807 /var/run/docker/libcontainerd/7b850a1d614f08369b9eafe1fc5b85500fdfa6e...
           ├─13002 docker-containerd-shim fbddca6db2ee011fec56d591e8ab6074435644c82fe7f212b80474964df29a39 /var/run/docker/libcontainerd/fbddca6db2ee011fec56d591e8ab6074435644c...
           ├─16762 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 7217 -container-ip 172.17.0.12 -container-port 3000
           ├─16767 docker-containerd-shim bc0838d6c4bec73a18c9fb32f1664f12fd454ef85ec22612b840c20fb7c73435 /var/run/docker/libcontainerd/bc0838d6c4bec73a18c9fb32f1664f12fd454ef...
           ├─17427 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9026 -container-ip 172.17.0.3 -container-port 3000
           ├─17433 docker-containerd-shim 53c187e590227218177bfe70be258f126c104b434fdfc544baa16f8e16672865 /var/run/docker/libcontainerd/53c187e590227218177bfe70be258f126c104b4...
           ├─25831 /usr/bin/docker daemon --dns 10.1.1.225 --log-driver=journald --storage-driver overlay -H unix:///var/run/docker.sock
           ├─25837 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc
           ├─26048 docker-containerd-shim 5a8b55710719cc5d800a066fb903fb76e9a805b4e98f7c55aed23fb013259f04 /var/run/docker/libcontainerd/5a8b55710719cc5d800a066fb903fb76e9a805b...
           ├─27583 docker-containerd-shim c601146c3ca5564494294d53cb82bd12c8c5c142ccd3431bcf3081f46166611a /var/run/docker/libcontainerd/c601146c3ca5564494294d53cb82bd12c8c5c14...
           ├─28008 docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 153 -container-ip 172.17.0.2 -container-port 53
           ├─28017 docker-proxy -proto udp -host-ip 0.0.0.0 -host-port 153 -container-ip 172.17.0.2 -container-port 53
           └─28023 docker-containerd-shim f8c4796d74605e4672a784c6b8cf08127f90e63545c2ca3a853827724d91aa60 /var/run/docker/libcontainerd/f8c4796d74605e4672a784c6b8cf08127f90e63...

May 31 03:36:05 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:05,994] INFO Received resource offers (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:82)
May 31 03:36:05 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:05,994] INFO No tasks scheduled or next task has been disabled.
May 31 03:36:05 k4b4-mantl-worker-001 docker[25831]:  (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:131)
May 31 03:36:05 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:05,994] INFO Declining unused offers. (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:89)
May 31 03:36:05 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:05,994] INFO Declined unused offers with filter refuseSeconds=5.0 (use --decline_offer_duration...mework:97)
May 31 03:36:06 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:06,994] INFO Received resource offers (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:82)
May 31 03:36:06 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:06,995] INFO No tasks scheduled or next task has been disabled.
May 31 03:36:06 k4b4-mantl-worker-001 docker[25831]:  (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:131)
May 31 03:36:06 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:06,995] INFO Declining unused offers. (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:89)
May 31 03:36:06 k4b4-mantl-worker-001 docker[25831]: [2016-05-31 03:36:06,995] INFO Declined unused offers with filter refuseSeconds=5.0 (use --decline_offer_duration...mework:97)
```
In the logs, nothing too crazy
```
May 30 21:53:20 k4b4-mantl-worker-001 NetworkManager[28613]: <info>  (docker0): bridge port veth6837e9b was attached
May 30 21:53:20 k4b4-mantl-worker-001 NetworkManager[28613]: <info>  (veth6837e9b): enslaved to docker0
May 30 21:53:20 k4b4-mantl-worker-001 kernel: docker0: port 7(veth6837e9b) entered forwarding state
May 30 21:53:20 k4b4-mantl-worker-001 kernel: docker0: port 7(veth6837e9b) entered forwarding state
May 30 21:53:35 k4b4-mantl-worker-001 kernel: docker0: port 7(veth6837e9b) entered forwarding state
May 30 22:26:13 k4b4-mantl-worker-001 kernel: Task in /docker/59ea4628a0006b05295396ac5e194c49f38127e77259e1181ab9f1be104b174f killed as a result of limit of /docker/59ea4628a0006b05295396ac5e194c49f38127e77259e1181ab9f1be104b174f
May 30 22:26:13 k4b4-mantl-worker-001 kernel: Memory cgroup stats for /docker/59ea4628a0006b05295396ac5e194c49f38127e77259e1181ab9f1be104b174f: cache:0KB rss:524288KB rss_huge:34816KB mapped_file:0KB swap:0KB inactive_anon:0KB active_anon:524248KB inactive_file:0KB active_file:0KB unevictable:0KB
May 30 22:26:13 k4b4-mantl-worker-001 kernel: Task in /docker/59ea4628a0006b05295396ac5e194c49f38127e77259e1181ab9f1be104b174f killed as a result of limit of /docker/59ea4628a0006b05295396ac5e194c49f38127e77259e1181ab9f1be104b174f
```

**Comment by ryane** [comment] 2016-05-31 11:42
If you run `docker ps` manually, does it respond? it looks like the `docker ps -a --format {{.Image}}\t{{.Status}}\t{{.Names}}` is from distributive checks (https://github.com/CiscoCloud/distributive/blob/896d6c746f247e5248be73b100f9bc61dee754dd/dockerstatus/dockerstatus.go#L51). I'm guessing it is a symptom of the docker hang and not the cause. but I wonder if we can do something in distributive to detect when this happens. @siddharthist what do you think?

this might be more of a general docker issue. We still occasionally see docker get stuck (less frequently in recent releases) and if you look at the open issues in the docker repo, there are several unresolved "hang" problems. You might be able to get a stack trace if you send `SIGUSR1` to the docker daemon - it might be helpful to compare it against other docker bug reports. otherwise, you might try restarting docker to see if things start working normally again.

**Comment by stevendborrelli** [comment] 2016-05-31 12:21
This is an issue with docker that might be getting triggered by our docker-gc package, or anything else that calls multiple operations to the docker daemon. 

We've had numerous docker conditions where it hangs across the versions for both Redhat and Docker compiled versions. Do a google search for `docker daemon hangs` and you will see a bunch of issues. 

I can update the docker-gc package to do an `xargs -n 1`so that it is not trying to mass delete container images. Outside of that we have to wait for docker to fix their internal issues.

A temporary fix is to stop the docker daemon, kill all docker processes and then restart the docker daemon.

**Comment by kbroughton** [comment] 2016-05-31 12:28
Thanks,

I will try the SIGUSR1 next time.  It's the second time in about 1000 operating hours.
What i did to resolve was:
```
systemctl stop docker
```
after two minutes it was still hung so I did a Ctrl+C and tried again.  The second time, after a minute it successfully shut down.
```
systemctl start docker
```
I did not manually kill any process.  It seems to be working fine.
I'm not 100% sure, but I feel like the last time it happened was also around the time I tried to fix kibana ui errors / re-loading the framework.  
I'll keep a closer eye next time i fiddle with kibaba.

**Comment by kbroughton** [comment] 2016-05-31 12:31
Perhaps the distributive checks could test that 
```
docker ps
```
returns in a reasonable time.  If not, the UI health-checks could clearly pinpoint that docker-daemon seems hung.

**Comment by siddharthist** [comment] 2016-05-31 12:51
I will make a distributive check to see if the Docker daemon is responding within a given timeout. I will also make sure that if the commands are hanging that long, distributive kills them and moves on.

**Comment by kbroughton** [comment] 2016-06-01 15:23
I also noticed that systemctl without any args gives a whole list of all running services.  nginx-consul was red and text indicated 'failed'.  All others were good.  Perhaps a catch-all distributive check would be helpful.

**Comment by siddharthist** [comment] 2016-06-01 16:56
@kbroughton There is a check for nginx-consul, in the Consul role's distributive checks. Was/is that giving a false positive?

**Comment by siddharthist** [comment] 2016-07-19 08:59
Closing since there's not much we can do about docker daemon latency.

**Closed by siddharthist** 2016-07-19 08:59 UTC
Labels: bug
