### ISSUE TITLE
Document adding nodes to bare-metal deployment

### ISSUE THREAD

**Issue by distributorofpain** [CiscoCloud/mantl#1337] opened 2016-04-10 07:13 UTC
Add section for adding nodes

-update host file on deployment node or Add DNS entry to DNS server(s)
-ensure disk is setup same way on new node(s)
-Update Inventory file with new node(s)
-rerun deployment 
```
ansible-playbook -u centos -i inventory \
        -e provider=bare-metal \
        -e consul_dc=dc1 \
        -e docker-lvm-backed=true \
        -e docker_lvm_data_volume_size="80%FREE" \
        -e @security.yml  sample.yml >& bare-metal.log2
```

**Comment by siddharthist** [comment] 2016-04-10 21:45
Closing as a duplicate of #1216, I'll add your info there. Thanks for outlining how this works on bare metal!

**Closed by siddharthist** 2016-04-10 21:45 UTC
Labels: docs, duplicate, provider/bare-metal
