### ISSUE TITLE
elasticsearch_client health check keeps failing, redeploying in marathon

### ISSUE THREAD

**Issue by dutronlabs** [CiscoCloud/mantl#1424] opened 2016-05-05 19:55 UTC
After ELK addon is installed (via ansible), seeing the following: 

Marathon - 
```
Warning: Health check 'HTTP /_cluster/health' failed.
```

I also tried this with the steps provided in #1318, got the same error. 

- Ansible version (`ansible --version`): 1.9.4
- Python version (`python --version`): 2.7.5
- Git commit hash or branch: master:latest
- Cloud Environment: GCE
- Terraform version (`terraform version`): 0.6.13

**Comment by ryane** [comment] 2016-05-05 23:18
can you take a look at the stdout and stderr logs for the elasticsearch-client task from the Mesos UI? Hopefully, there will be some output that will indicate what the problem is. Feel free to post here.

**Comment by distributorofpain** [comment] 2016-05-08 02:15
I am seeing this too!  I just deployed a completely fresh deployment in DO, but i see this after running the addon install.

```
curl: (28) Connection timed out after 5002 milliseconds
The Elasticsearch cluster is not healthy.
```

Requested output below since @dutronlabs  hasnt had a chance yet.

**stderr**
```
I0508 01:35:19.200503 29778 exec.cpp:134] Version: 0.25.0
I0508 01:35:19.213757 29779 exec.cpp:208] Executor registered on slave d7a7c055-338b-4291-90f3-37d8164c3271-S4
Warning: '-c' is deprecated, it will be replaced by '--cpu-shares' soon. See usage.
+ export ELASTICSEARCH_SERVICE=transport_port.elasticsearch-executor-mantl
+ ELASTICSEARCH_SERVICE=transport_port.elasticsearch-executor-mantl
+ export ELASTICSEARCH_CLUSTER_NAME=mantl
+ ELASTICSEARCH_CLUSTER_NAME=mantl
+ CONSUL_TEMPLATE=/usr/local/bin/consul-template
+ CONSUL_CONFIG=/consul-template/config.d
+ CONSUL_CONNECT=consul.service.consul:8500
+ CONSUL_MINWAIT=30s
+ CONSUL_MAXWAIT=60s
+ CONSUL_LOGLEVEL=warn
+ CONSUL_SSL_VERIFY=false
++ awk '{ print $1 ; exit }'
++ getent hosts mantl-do-nyc2-worker-002
+ export PUBLISH_HOST=10.128.26.24
+ PUBLISH_HOST=10.128.26.24
+ [[ -n consul.service.consul:8500 ]]
+ ctargs=' -consul consul.service.consul:8500'
+ [[ -n true ]]
+ ctargs=' -consul consul.service.consul:8500 -ssl'
+ [[ -n true ]]
+ ctargs=' -consul consul.service.consul:8500 -ssl -ssl-verify=false'
+ [[ -n '' ]]
+ ATTEMPT=0
+ wait_for_service
+ /usr/local/bin/consul-template -config /consul-template/config.d -log-level warn -wait 30s:60s -once -consul consul.service.consul:8500 -ssl -ssl-verify=false
2016/05/08 01:35:20 [WARN] (runner) disabling consul SSL verification
+ grep discovery.zen.ping.unicast.hosts /usr/share/elasticsearch/config/elasticsearch.yml
+ [[ 0 -eq 5 ]]
+ exec /docker-entrypoint.sh elasticsearch
[ZoneTransfer]
ZoneId=3
```

**stdout**
```
--container="mesos-d7a7c055-338b-4291-90f3-37d8164c3271-S4.d9db25f5-7672-4ebe-90ca-2e7683c828bc" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slaves/d7a7c055-338b-4291-90f3-37d8164c3271-S4/frameworks/0bfd2cbe-2cb8-4462-b97c-7ba71086d010-0000/executors/mantl_elasticsearch-client.1f66e3f1-14bd-11e6-b361-a6c256ed5ea8/runs/d9db25f5-7672-4ebe-90ca-2e7683c828bc" --stop_timeout="0ns"
--container="mesos-d7a7c055-338b-4291-90f3-37d8164c3271-S4.d9db25f5-7672-4ebe-90ca-2e7683c828bc" --docker="docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/var/lib/mesos/slaves/d7a7c055-338b-4291-90f3-37d8164c3271-S4/frameworks/0bfd2cbe-2cb8-4462-b97c-7ba71086d010-0000/executors/mantl_elasticsearch-client.1f66e3f1-14bd-11e6-b361-a6c256ed5ea8/runs/d9db25f5-7672-4ebe-90ca-2e7683c828bc" --stop_timeout="0ns"
Registered docker executor on mantl-do-nyc2-worker-002
Starting task mantl_elasticsearch-client.1f66e3f1-14bd-11e6-b361-a6c256ed5ea8
[2016-05-08 01:35:53,893][INFO ][node                     ] [Spellbinder] version[2.1.1], pid[16], build[40e2c53/2015-12-15T13:05:55Z]
[2016-05-08 01:35:53,897][INFO ][node                     ] [Spellbinder] initializing ...
[2016-05-08 01:35:54,194][INFO ][plugins                  ] [Spellbinder] loaded [], sites []
[2016-05-08 01:35:59,132][INFO ][node                     ] [Spellbinder] initialized
[2016-05-08 01:35:59,132][INFO ][node                     ] [Spellbinder] starting ...
[2016-05-08 01:35:59,351][INFO ][transport                ] [Spellbinder] publish_address {10.128.26.24:9300}, bound_addresses {[::]:9300}
[2016-05-08 01:35:59,388][INFO ][discovery                ] [Spellbinder] mantl/pyTOiGWHRv27DbhE3AUc_w
[2016-05-08 01:36:02,583][INFO ][cluster.service          ] [Spellbinder] detected_master {Jekyll}{bb3xVvRgQS-mkQFFUBUgRQ}{162.243.103.82}{162.243.103.82:4001}{local=false, master=true}, added {{Jekyll}{bb3xVvRgQS-mkQFFUBUgRQ}{162.243.103.82}{162.243.103.82:4001}{local=false, master=true},}, reason: zen-disco-receive(from master [{Jekyll}{bb3xVvRgQS-mkQFFUBUgRQ}{162.243.103.82}{162.243.103.82:4001}{local=false, master=true}])
[2016-05-08 01:36:02,620][INFO ][http                     ] [Spellbinder] publish_address {10.128.26.24:9200}, bound_addresses {[::]:9200}
[2016-05-08 01:36:02,621][INFO ][node                     ] [Spellbinder] started
[ZoneTransfer]
ZoneId=3
```

**Comment by distributorofpain** [comment] 2016-05-08 02:19
Add this image of the health checks to see if that helps at all:
![image](https://cloud.githubusercontent.com/assets/18275482/15095667/b7b35c22-14a1-11e6-9a2a-e30ce23b1dc6.png)

**Comment by ryane** [comment] 2016-05-09 14:17
I am not setup to test digitalocean right now but I can't repro on GCE. I don't see anything obvious in the logs. The elasticsearch-client health check hits the `/_cluster/health` elasticsearch endpoint. Can you manually check that to see what the issue is? You can find the host/port it is running on via marathon.

**Comment by distributorofpain** [comment] 2016-05-10 03:36
mantl-do-nyc2-worker-002:[9200, 9300]  How would i a manual health check?  Telnet to the port?

**Comment by distributorofpain** [comment] 2016-05-10 03:39
This is interesting..  on the marathon peice under configuration:

Container
```
{
  "type": "DOCKER",
  "volumes": [],
  "docker": {
    "image": "ciscocloud/mantl-elasticsearch-client:2.1.1",
    "network": "BRIDGE",
    "portMappings": [
      {
        "containerPort": 9200,
        "hostPort": 9200,
        "servicePort": 10003,
        "protocol": "tcp"
      },
      {
        "containerPort": 9300,
        "hostPort": 9300,
        "servicePort": 10004,
        "protocol": "tcp"
      }
    ],
    "privileged": false,
    "parameters": [],
    "forcePullImage": false
  }
}
```

Then Health Checks:
```
[
  {
    "path": "/_cluster/health",
    "protocol": "HTTP",
    "portIndex": 0,
    "gracePeriodSeconds": 30,
    "intervalSeconds": 30,
    "timeoutSeconds": 10,
    "maxConsecutiveFailures": 5,
    "ignoreHttp1xx": false
  }
]
```

**Comment by siddharthist** [comment] 2016-05-10 04:48
@distributorofpain You'll want to run a `curl` command, that's what Consul is doing. I _think_ that 
```bash
curl -Lk <your-node>:9200/_cluster/health
```
should do it, where `<your-node>` is the IP address you got from the Marathon dashboard, as @ryane mentioned.

**Comment by distributorofpain** [comment] 2016-05-10 15:38
Output of that ( i tried both interfaces, both had the same result ):
```
 curl -lk 10.128.26.24:9200/_cluster/health
{"cluster_name":"mantl","status":"green","timed_out":false,"number_of_nodes":2,"number_of_data_nodes":1,"active_primary_shards":16,"active_shards":16,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

**Comment by ryane** [comment] 2016-05-10 18:23
@distributorofpain that is showing that your `elasticsearch-client-mantl` service is actually healthy. Looking back on the thread, I see you were reporting something slightly different than the original issue. It looks like your `elasticsearch-mantl` service is unhealthy - that is the service for the mesos framework (https://github.com/mesos/elasticsearch) itself - not the client node. You can find the host it is running on by looking at the `mantl/elasticsearch` app in marathon (the port should be 31100 unless you customized your install).

Run

`curl host:31100/v1/tasks`

That will return some json that lists every elasticsearch node that the framework started. Then, curl the health endpoint `/_cluster/health` for each http address in the resulting json. Hopefully, that will tell us something.

**Comment by distributorofpain** [comment] 2016-05-10 21:50
response for 31100 is:
```
curl -lk 162.243.19.243:31100/v1/tasks
[{"id":"elasticsearch_mantl-do-nyc2-worker-002_20160508T011438.260Z","state":"TASK_RUNNING","name":"elasticsearch-executor-mantl","version":"1.0.1","started_at":"2016-05-08T01:14:38.452Z","http_address":"10.128.26.24:4000","transport_address":"10.128.26.24:4001","hostname":"mantl-do-nyc2-worker-002"}
```

Then i ran this against the only server in the output above:
```
curl -lk 10.128.26.24:4000/_cluster/health
{"cluster_name":"mantl","status":"green","timed_out":false,"number_of_nodes":2,"number_of_data_nodes":1,"active_primary_shards":16,"active_shards":16,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":0,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0,"task_max_waiting_in_queue_millis":0,"active_shards_percent_as_number":100.0}
```

**Comment by distributorofpain** [comment] 2016-05-10 21:51
If i run it against the transport_address noted there, i get the following:
```
 curl -lk 10.128.26.24:4001/_cluster/health
This is not a HTTP port
```

**Comment by ryane** [comment] 2016-05-11 13:30
@distributorofpain that error from the transport port is expected. but I am not sure what your issue is. all of the health check commands are reporting that your install is healthy. are you still seeing failing health checks? is your elasticsearch instance working otherwise?

**Comment by distributorofpain** [comment] 2016-05-12 05:42
yes, everything is working, just have that health check error.

Maybe something wrong with the check script?

```
check_script=if [[ "$(node=$(curl --silent --show-error --fail --retry 2 --connect-timeout 5 --max-time 5 http://{host}:{port}/v1/tasks/ | jq -r '.[0].http_address') && curl --silent --show-error --fail --retry 2 --connect-timeout 5 --max-time 5 http://$node/_cluster/health | jq -r .status)" != "green" ]]; then echo The Elasticsearch cluster is not healthy.; exit 1; fi;
```

**Comment by distributorofpain** [comment] 2016-05-12 05:44
I should note that this issue doesnt show up in my bare metal deployment, though i think the code version is older due to the fact that kubernetes was added in the build i used for DO.  Perhaps something was updated in the code between april and may?

**Comment by ryane** [comment] 2016-05-12 21:43
I don't see this problem in master (but haven't tested DO explicitly). 

does the consul service for `elasticsearch-mantl` have the write host and port registered? you can find it in the ui or hitting the consul api from one of your nodes. for example:

```
curl http://localhost:8500/v1/catalog/service/elasticsearch-mantl | jq .
```

If it is correct, the only thing I can think of is to break down that health check into a series of curl commands and see if you can figure out where it is broken.

**Comment by distributorofpain** [comment] 2016-05-13 02:25
![image](https://cloud.githubusercontent.com/assets/18275482/15236208/78a734ac-1890-11e6-9c18-525630fbe899.png)

**Comment by distributorofpain** [comment] 2016-05-15 17:59
i had to rebuild the cluster in DO due to a failed worker expansion.  After rebuild the error is no longer there, all healthchecks are clean.

**Comment by siddharthist** [comment] 2016-05-15 19:40
Since this issue has been unreproducable, I'm going to close this.

**Closed by siddharthist** 2016-05-15 19:40 UTC
Labels: addons/elk
