### ISSUE TITLE
VM snapshots for fast provisioning 

### ISSUE THREAD

**Issue by mcapuccini** [CiscoCloud/mantl#1186] opened 2016-03-01 09:28 UTC
I have been now using MANTL for a while, and we would like to use it my group to rapidly deploy applications. One major problem in achieving fast deployment/scalability is that it takes long time to deploy software via Ansible. I think this can be done faster having some snapshots of the various entities (control/edge/resource), and booting from the point where the machines are already provisioned. I think this would be a nice improvement, did you think about that?

**Comment by siddharthist** [comment] 2016-03-01 18:21
We currently build a Vagrant image that has software preinstalled. The issue is mostly that many parts of provisioning depend on information that is available at that time (IPs, secrets, etc). 

How could we improve our image?

**Comment by mcapuccini** [comment] 2016-03-02 13:28
I think you should enable some mechanism to boot that image on cloud, and then write up some notebooks to just inject the IPs, secret etc... Would this be problematic?

**Comment by siddharthist** [comment] 2016-03-02 18:52
@mcapuccini I'm not sure I understand what you mean. Are you talking about images for cloud providers, or for Vagrant? This might be a duplicate of #992. 

Currently, if some package is installed or a machine is configured properly, Ansible returns `ok` for that step and doesn't change anything. This makes the provisioning process much faster where we use our own images (as of right now, just Vagrant).

**Comment by mcapuccini** [comment] 2016-03-02 21:59
@siddharthist I am talking about cloud providers. I didn't know that Ansible has this feature, this is great. We have a OpenStack cluster, I will have to look into Packer at a certain point. I'll ping you if I get anything working.

**Comment by siddharthist** [comment] 2016-03-02 22:01
@mcapuccini Thanks for the input! I'm going to close this now since cloud images are already in our issues/roadmap. We'd love to hear more feedback/results on the issue referenced above.

**Closed by siddharthist** 2016-03-02 22:01 UTC
Labels: provider/vagrant
